package BoggledGame;


/**
* BoggledGame/BoggledInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
public abstract class BoggledInterfacePOA extends org.omg.PortableServer.Servant
 implements BoggledGame.BoggledInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("timeChecker", new java.lang.Integer (1));
    _methods.put ("roundTime", new java.lang.Integer (2));
    _methods.put ("removePlayer", new java.lang.Integer (3));
    _methods.put ("startGame", new java.lang.Integer (4));
    _methods.put ("getLetters", new java.lang.Integer (5));
    _methods.put ("startRound", new java.lang.Integer (6));
    _methods.put ("sendWord", new java.lang.Integer (7));
    _methods.put ("getWinner", new java.lang.Integer (8));
    _methods.put ("getTopPlayers", new java.lang.Integer (9));
    _methods.put ("playerWins", new java.lang.Integer (10));
    _methods.put ("logout", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Login a player
       case 0:  // BoggledGame/BoggledInterface/login
       {
         try {
           BoggledGame.Player gamePlayer = BoggledGame.PlayerHelper.read (in);
           this.login (gamePlayer);
           out = $rh.createReply();
         } catch (BoggledGame.LoginException $ex) {
           out = $rh.createExceptionReply ();
           BoggledGame.LoginExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Check the time remaining in the lobby (before the game starts)
       case 1:  // BoggledGame/BoggledInterface/timeChecker
       {
         String gameId = in.read_string ();
         int $result = (int)0;
         $result = this.timeChecker (gameId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // Check the time remaining in the current round
       case 2:  // BoggledGame/BoggledInterface/roundTime
       {
         String gameId = in.read_string ();
         int $result = (int)0;
         $result = this.roundTime (gameId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // Remove a player from a game
       case 3:  // BoggledGame/BoggledInterface/removePlayer
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         this.removePlayer (player, gameId);
         out = $rh.createReply();
         break;
       }


  // Start a new game with the given players
       case 4:  // BoggledGame/BoggledInterface/startGame
       {
         try {
           BoggledGame.Player players = BoggledGame.PlayerHelper.read (in);
           BoggledGame.Game $result = null;
           $result = this.startGame (players);
           out = $rh.createReply();
           BoggledGame.GameHelper.write (out, $result);
         } catch (BoggledGame.StartGameException $ex) {
           out = $rh.createExceptionReply ();
           BoggledGame.StartGameExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Get the random letters for the current round
       case 5:  // BoggledGame/BoggledInterface/getLetters
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         BoggledGame.Round $result = null;
         $result = this.getLetters (player, gameId);
         out = $rh.createReply();
         BoggledGame.RoundHelper.write (out, $result);
         break;
       }


  // Start a new round
       case 6:  // BoggledGame/BoggledInterface/startRound
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         boolean $result = false;
         $result = this.startRound (player, gameId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Send a word from a player
       case 7:  // BoggledGame/BoggledInterface/sendWord
       {
         try {
           BoggledGame.Words word = BoggledGame.WordsHelper.read (in);
           boolean $result = false;
           $result = this.sendWord (word);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (BoggledGame.SendWordException $ex) {
           out = $rh.createExceptionReply ();
           BoggledGame.SendWordExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Get the winner of the current round
       case 8:  // BoggledGame/BoggledInterface/getWinner
       {
         String gameId = in.read_string ();
         BoggledGame.Round $result = null;
         $result = this.getWinner (gameId);
         out = $rh.createReply();
         BoggledGame.RoundHelper.write (out, $result);
         break;
       }


  // Get the top players (e.g. players with the most wins, etc.)
       case 9:  // BoggledGame/BoggledInterface/getTopPlayers
       {
         BoggledGame.TopPlayers $result = null;
         $result = this.getTopPlayers ();
         out = $rh.createReply();
         BoggledGame.TopPlayersHelper.write (out, $result);
         break;
       }


  // Update the game state to reflect a player's win
       case 10:  // BoggledGame/BoggledInterface/playerWins
       {
         BoggledGame.Game games = BoggledGame.GameHelper.read (in);
         BoggledGame.Game $result = null;
         $result = this.playerWins (games);
         out = $rh.createReply();
         BoggledGame.GameHelper.write (out, $result);
         break;
       }


  // Logout a player
       case 11:  // BoggledGame/BoggledInterface/logout
       {
         BoggledGame.Player players = BoggledGame.PlayerHelper.read (in);
         boolean $result = false;
         $result = this.logout (players);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledGame/BoggledInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BoggledInterface _this() 
  {
    return BoggledInterfaceHelper.narrow(
    super._this_object());
  }

  public BoggledInterface _this(org.omg.CORBA.ORB orb) 
  {
    return BoggledInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class BoggledInterfacePOA
