package BoggledGame;


/**
* BoggledGame/BoggledInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
public interface BoggledInterface extends BoggledInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggledInterface
