package BoggledGame;

/**
* BoggledGame/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (BoggledGame.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.PlayerHelper.type ();
  }

}
