package BoggledGame;

/**
* BoggledGame/RoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class RoundHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.Round value = null;

  public RoundHolder ()
  {
  }

  public RoundHolder (BoggledGame.Round initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.RoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.RoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.RoundHelper.type ();
  }

}
