package BoggledGame;


/**
* BoggledGame/GameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

abstract public class GameHelper
{
  private static String  _id = "IDL:BoggledGame/Game:1.0";

  public static void insert (org.omg.CORBA.Any a, Game that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Game extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = PlayerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "players",
            _tcOf_members0,
            null);
          _tcOf_members0 = RoundHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "rounds",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "winner",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "roundTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "roundWins",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[6] = new org.omg.CORBA.StructMember (
            "isGameOver",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "winnerScore",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (GameHelper.id (), "Game", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Game read (org.omg.CORBA.portable.InputStream istream)
  {
    Game value = new Game ();
    value.id = istream.read_string ();
    int _len0 = istream.read_long ();
    value.players = new Player[_len0];
    for (int _o1 = 0;_o1 < value.players.length; ++_o1)
      value.players[_o1] = PlayerHelper.read (istream);
    int _len1 = istream.read_long ();
    value.rounds = new Round[_len1];
    for (int _o2 = 0;_o2 < value.rounds.length; ++_o2)
      value.rounds[_o2] = RoundHelper.read (istream);
    value.winner = istream.read_string ();
    value.roundTime = istream.read_long ();
    value.roundWins = istream.read_long ();
    value.isGameOver = istream.read_boolean ();
    value.winnerScore = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Game value)
  {
    ostream.write_string (value.id);
    ostream.write_long (value.players.length);
    for (int _i0 = 0;_i0 < value.players.length; ++_i0)
      PlayerHelper.write (ostream, value.players[_i0]);
    ostream.write_long (value.rounds.length);
    for (int _i1 = 0;_i1 < value.rounds.length; ++_i1)
      RoundHelper.write (ostream, value.rounds[_i1]);
    ostream.write_string (value.winner);
    ostream.write_long (value.roundTime);
    ostream.write_long (value.roundWins);
    ostream.write_boolean (value.isGameOver);
    ostream.write_long (value.winnerScore);
  }

}
