package BoggledGame;


/**
* BoggledGame/_BoggledInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
public class _BoggledInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements BoggledGame.BoggledInterface
{


  // Login a player
  public void login (BoggledGame.Player gamePlayer) throws BoggledGame.LoginException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                BoggledGame.PlayerHelper.write ($out, gamePlayer);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoggledGame/LoginException:1.0"))
                    throw BoggledGame.LoginExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                login (gamePlayer        );
            } finally {
                _releaseReply ($in);
            }
  } // login


  // Check the time remaining in the lobby (before the game starts)
  public int timeChecker (String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("timeChecker", true);
                $out.write_string (gameId);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return timeChecker (gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // timeChecker


  // Check the time remaining in the current round
  public int roundTime (String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("roundTime", true);
                $out.write_string (gameId);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return roundTime (gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // roundTime


  // Remove a player from a game
  public void removePlayer (String player, String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removePlayer", true);
                $out.write_string (player);
                $out.write_string (gameId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removePlayer (player, gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // removePlayer


  // Start a new game with the given players
  public BoggledGame.Game startGame (BoggledGame.Player players) throws BoggledGame.StartGameException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                BoggledGame.PlayerHelper.write ($out, players);
                $in = _invoke ($out);
                BoggledGame.Game $result = BoggledGame.GameHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoggledGame/StartGameException:1.0"))
                    throw BoggledGame.StartGameExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (players        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame


  // Get the random letters for the current round
  public BoggledGame.Round getLetters (String player, String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLetters", true);
                $out.write_string (player);
                $out.write_string (gameId);
                $in = _invoke ($out);
                BoggledGame.Round $result = BoggledGame.RoundHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLetters (player, gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // getLetters


  // Start a new round
  public boolean startRound (String player, String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_string (player);
                $out.write_string (gameId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (player, gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound


  // Send a word from a player
  public boolean sendWord (BoggledGame.Words word) throws BoggledGame.SendWordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendWord", true);
                BoggledGame.WordsHelper.write ($out, word);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoggledGame/SendWordException:1.0"))
                    throw BoggledGame.SendWordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sendWord (word        );
            } finally {
                _releaseReply ($in);
            }
  } // sendWord


  // Get the winner of the current round
  public BoggledGame.Round getWinner (String gameId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getWinner", true);
                $out.write_string (gameId);
                $in = _invoke ($out);
                BoggledGame.Round $result = BoggledGame.RoundHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getWinner (gameId        );
            } finally {
                _releaseReply ($in);
            }
  } // getWinner


  // Get the top players (e.g. players with the most wins, etc.)
  public BoggledGame.TopPlayers getTopPlayers ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTopPlayers", true);
                $in = _invoke ($out);
                BoggledGame.TopPlayers $result = BoggledGame.TopPlayersHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTopPlayers (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTopPlayers


  // Update the game state to reflect a player's win
  public BoggledGame.Game playerWins (BoggledGame.Game games)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("playerWins", true);
                BoggledGame.GameHelper.write ($out, games);
                $in = _invoke ($out);
                BoggledGame.Game $result = BoggledGame.GameHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return playerWins (games        );
            } finally {
                _releaseReply ($in);
            }
  } // playerWins


  // Logout a player
  public boolean logout (BoggledGame.Player players)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logout", true);
                BoggledGame.PlayerHelper.write ($out, players);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return logout (players        );
            } finally {
                _releaseReply ($in);
            }
  } // logout

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledGame/BoggledInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "BoggledGame._BoggledInterfaceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BoggledInterfaceStub
