package BoggledGame;


/**
* BoggledGame/BoggledInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
abstract public class BoggledInterfaceHelper
{
  private static String  _id = "IDL:BoggledGame/BoggledInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, BoggledGame.BoggledInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoggledGame.BoggledInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BoggledGame.BoggledInterfaceHelper.id (), "BoggledInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoggledGame.BoggledInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BoggledInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoggledGame.BoggledInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BoggledGame.BoggledInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoggledGame.BoggledInterface)
      return (BoggledGame.BoggledInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoggledGame._BoggledInterfaceStub stub = new BoggledGame._BoggledInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BoggledGame.BoggledInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoggledGame.BoggledInterface)
      return (BoggledGame.BoggledInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoggledGame._BoggledInterfaceStub stub = new BoggledGame._BoggledInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
