package BoggledGame;


/**
* BoggledGame/BoggledInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
public interface BoggledInterfaceOperations 
{

  // Login a player
  void login (BoggledGame.Player gamePlayer) throws BoggledGame.LoginException;

  // Check the time remaining in the lobby (before the game starts)
  int timeChecker (String gameId);

  // Check the time remaining in the current round
  int roundTime (String gameId);

  // Remove a player from a game
  void removePlayer (String player, String gameId);

  // Start a new game with the given players
  BoggledGame.Game startGame (BoggledGame.Player players) throws BoggledGame.StartGameException;

  // Get the random letters for the current round
  BoggledGame.Round getLetters (String player, String gameId);

  // Start a new round
  boolean startRound (String player, String gameId);

  // Send a word from a player
  boolean sendWord (BoggledGame.Words word) throws BoggledGame.SendWordException;

  // Get the winner of the current round
  BoggledGame.Round getWinner (String gameId);

  // Get the top players (e.g. players with the most wins, etc.)
  BoggledGame.TopPlayers getTopPlayers ();

  // Update the game state to reflect a player's win
  BoggledGame.Game playerWins (BoggledGame.Game games);

  // Logout a player
  boolean logout (BoggledGame.Player players);
} // interface BoggledInterfaceOperations
