package BoggledGame;

/**
* BoggledGame/BoggledInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/


// Define the BoggledInterface interface
public final class BoggledInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.BoggledInterface value = null;

  public BoggledInterfaceHolder ()
  {
  }

  public BoggledInterfaceHolder (BoggledGame.BoggledInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.BoggledInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.BoggledInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.BoggledInterfaceHelper.type ();
  }

}
