package BoggledGame;


/**
* BoggledGame/Game.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class Game implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  // unique ID for this game
  public BoggledGame.Player players[] = null;

  // list of players in this game
  public BoggledGame.Round rounds[] = null;

  // list of rounds played in this game
  public String winner = null;

  // username of the overall winner of the game (if any)
  public int roundTime = (int)0;
  public int roundWins = (int)0;
  public boolean isGameOver = false;
  public int winnerScore = (int)0;

  public Game ()
  {
  } // ctor

  public Game (String _id, BoggledGame.Player[] _players, BoggledGame.Round[] _rounds, String _winner, int _roundTime, int _roundWins, boolean _isGameOver, int _winnerScore)
  {
    id = _id;
    players = _players;
    rounds = _rounds;
    winner = _winner;
    roundTime = _roundTime;
    roundWins = _roundWins;
    isGameOver = _isGameOver;
    winnerScore = _winnerScore;
  } // ctor

} // class Game
