package BoggledGame;

/**
* BoggledGame/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (BoggledGame.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.GameHelper.type ();
  }

}
