package BoggledGame;

/**
* BoggledGame/LoginExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class LoginExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.LoginException value = null;

  public LoginExceptionHolder ()
  {
  }

  public LoginExceptionHolder (BoggledGame.LoginException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.LoginExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.LoginExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.LoginExceptionHelper.type ();
  }

}
