package BoggledGame;


/**
* BoggledGame/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;

  // player's username
  public String password = null;

  // player's password
  public short wins = (short)0;

  // number of wins for this player
  public int score = (int)0;

  public Player ()
  {
  } // ctor

  public Player (String _username, String _password, short _wins, int _score)
  {
    username = _username;
    password = _password;
    wins = _wins;
    score = _score;
  } // ctor

} // class Player
