package BoggledGame;

/**
* BoggledGame/SendWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class SendWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.SendWordException value = null;

  public SendWordExceptionHolder ()
  {
  }

  public SendWordExceptionHolder (BoggledGame.SendWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.SendWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.SendWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.SendWordExceptionHelper.type ();
  }

}
