package BoggledGame;

/**
* BoggledGame/StartGameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class StartGameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.StartGameException value = null;

  public StartGameExceptionHolder ()
  {
  }

  public StartGameExceptionHolder (BoggledGame.StartGameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.StartGameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.StartGameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.StartGameExceptionHelper.type ();
  }

}
