package BoggledGame;


/**
* BoggledGame/StartGameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class StartGameException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public StartGameException ()
  {
    super(StartGameExceptionHelper.id());
  } // ctor

  public StartGameException (String _reason)
  {
    super(StartGameExceptionHelper.id());
    reason = _reason;
  } // ctor


  public StartGameException (String $reason, String _reason)
  {
    super(StartGameExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class StartGameException
