package BoggledGame;

/**
* BoggledGame/TopPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class TopPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.TopPlayers value = null;

  public TopPlayersHolder ()
  {
  }

  public TopPlayersHolder (BoggledGame.TopPlayers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.TopPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.TopPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.TopPlayersHelper.type ();
  }

}
