package BoggledGame;


/**
* BoggledGame/TopPlayersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

abstract public class TopPlayersHelper
{
  private static String  _id = "IDL:BoggledGame/TopPlayers:1.0";

  public static void insert (org.omg.CORBA.Any a, BoggledGame.TopPlayers that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoggledGame.TopPlayers extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "topPlayer",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BoggledGame.TopPlayersHelper.id (), "TopPlayers", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoggledGame.TopPlayers read (org.omg.CORBA.portable.InputStream istream)
  {
    BoggledGame.TopPlayers value = new BoggledGame.TopPlayers ();
    int _len0 = istream.read_long ();
    value.topPlayer = new String[_len0];
    for (int _o1 = 0;_o1 < value.topPlayer.length; ++_o1)
      value.topPlayer[_o1] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoggledGame.TopPlayers value)
  {
    ostream.write_long (value.topPlayer.length);
    for (int _i0 = 0;_i0 < value.topPlayer.length; ++_i0)
      ostream.write_string (value.topPlayer[_i0]);
  }

}
