package BoggledGame;


/**
* BoggledGame/TopPlayers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class TopPlayers implements org.omg.CORBA.portable.IDLEntity
{
  public String topPlayer[] = null;

  public TopPlayers ()
  {
  } // ctor

  public TopPlayers (String[] _topPlayer)
  {
    topPlayer = _topPlayer;
  } // ctor

} // class TopPlayers
