package BoggledGame;

/**
* BoggledGame/WordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Wednesday, July 3, 2024 9:59:49 PM SGT
*/

public final class WordsHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledGame.Words value = null;

  public WordsHolder ()
  {
  }

  public WordsHolder (BoggledGame.Words initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledGame.WordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledGame.WordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledGame.WordsHelper.type ();
  }

}
