package BoggledGame;


/**
* BoggledGame/BoggledInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/


// Define the WordyInterface interface
public interface BoggledInterface extends BoggledInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggledInterface
