package BoggledGame;

/**
* BoggledGame/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameHelper.type ();
  }

}
