package BoggledGame;

/**
* BoggledGame/TopPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class TopPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public TopPlayers value = null;

  public TopPlayersHolder ()
  {
  }

  public TopPlayersHolder (TopPlayers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TopPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TopPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TopPlayersHelper.type ();
  }

}
