package BoggledGame;


/**
* BoggledGame/Words.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class Words implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;

  // ID of the game this word was sent for
  public String player = null;

  // username of the player who sent this word
  public String word = null;

  // the actual word sent by the player
  public int point = (int)0;

  public Words ()
  {
  } // ctor

  public Words (String _gameId, String _player, String _word, int _point)
  {
    gameId = _gameId;
    player = _player;
    word = _word;
    point = _point;
  } // ctor

} // class Words
