package BoggledGame;


/**
* BoggledGame/BoggledInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/


// Define the WordyInterface interface
public abstract class BoggledInterfacePOA extends org.omg.PortableServer.Servant
 implements BoggledInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new Integer (0));
    _methods.put ("timeChecker", new Integer (1));
    _methods.put ("roundTime", new Integer (2));
    _methods.put ("removePlayer", new Integer (3));
    _methods.put ("startGame", new Integer (4));
    _methods.put ("getLetters", new Integer (5));
    _methods.put ("startRound", new Integer (6));
    _methods.put ("sendWord", new Integer (7));
    _methods.put ("getWinner", new Integer (8));
    _methods.put ("getTopPlayers", new Integer (9));
    _methods.put ("playerWins", new Integer (10));
    _methods.put ("logout", new Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Login a player
       case 0:  // BoggledGame/BoggledInterface/login
       {
         try {
           Player gamePlayer = PlayerHelper.read (in);
           this.login (gamePlayer);
           out = $rh.createReply();
         } catch (LoginException $ex) {
           out = $rh.createExceptionReply ();
           LoginExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Check the time remaining in the lobby (before the game starts)
       case 1:  // BoggledGame/BoggledInterface/timeChecker
       {
         String gameId = in.read_string ();
         int $result = (int)0;
         $result = this.timeChecker (gameId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // Check the time remaining in the current round
       case 2:  // BoggledGame/BoggledInterface/roundTime
       {
         String gameId = in.read_string ();
         int $result = (int)0;
         $result = this.roundTime (gameId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // Remove a player from a game
       case 3:  // BoggledGame/BoggledInterface/removePlayer
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         this.removePlayer (player, gameId);
         out = $rh.createReply();
         break;
       }


  // Start a new game with the given players
       case 4:  // BoggledGame/BoggledInterface/startGame
       {
         try {
           Player players = PlayerHelper.read (in);
           Game $result = null;
           $result = this.startGame (players);
           out = $rh.createReply();
           GameHelper.write (out, $result);
         } catch (StartGameException $ex) {
           out = $rh.createExceptionReply ();
           StartGameExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Get the random letters for the current round
       case 5:  // BoggledGame/BoggledInterface/getLetters
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         Round $result = null;
         $result = this.getLetters (player, gameId);
         out = $rh.createReply();
         RoundHelper.write (out, $result);
         break;
       }


  // Start a new round
       case 6:  // BoggledGame/BoggledInterface/startRound
       {
         String player = in.read_string ();
         String gameId = in.read_string ();
         boolean $result = false;
         $result = this.startRound (player, gameId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Send a word from a player
       case 7:  // BoggledGame/BoggledInterface/sendWord
       {
         try {
           Words word = WordsHelper.read (in);
           boolean $result = false;
           $result = this.sendWord (word);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (SendWordException $ex) {
           out = $rh.createExceptionReply ();
           SendWordExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Get the winner of the current round
       case 8:  // BoggledGame/BoggledInterface/getWinner
       {
         String gameId = in.read_string ();
         Round $result = null;
         $result = this.getWinner (gameId);
         out = $rh.createReply();
         RoundHelper.write (out, $result);
         break;
       }


  // Get the top players (e.g. players with the most wins, etc.)
       case 9:  // BoggledGame/BoggledInterface/getTopPlayers
       {
         TopPlayers $result = null;
         $result = this.getTopPlayers ();
         out = $rh.createReply();
         TopPlayersHelper.write (out, $result);
         break;
       }


  // Update the game state to reflect a player's win
       case 10:  // BoggledGame/BoggledInterface/playerWins
       {
         Game games = GameHelper.read (in);
         Game $result = null;
         $result = this.playerWins (games);
         out = $rh.createReply();
         GameHelper.write (out, $result);
         break;
       }


  // Logout a player
       case 11:  // BoggledGame/BoggledInterface/logout
       {
         Player players = PlayerHelper.read (in);
         boolean $result = false;
         $result = this.logout (players);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledGame/BoggledInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BoggledInterface _this() 
  {
    return BoggledInterfaceHelper.narrow(
    super._this_object());
  }

  public BoggledInterface _this(org.omg.CORBA.ORB orb) 
  {
    return BoggledInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class BoggledInterfacePOA
