package BoggledGame;


/**
* BoggledGame/BoggledInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/


// Define the WordyInterface interface
public interface BoggledInterfaceOperations 
{

  // Login a player
  void login (Player gamePlayer) throws LoginException;

  // Check the time remaining in the lobby (before the game starts)
  int timeChecker (String gameId);

  // Check the time remaining in the current round
  int roundTime (String gameId);

  // Remove a player from a game
  void removePlayer (String player, String gameId);

  // Start a new game with the given players
  Game startGame (Player players) throws StartGameException;

  // Get the random letters for the current round
  Round getLetters (String player, String gameId);

  // Start a new round
  boolean startRound (String player, String gameId);

  // Send a word from a player
  boolean sendWord (Words word) throws SendWordException;

  // Get the winner of the current round
  Round getWinner (String gameId);

  // Get the top players (e.g. players with the most wins, etc.)
  TopPlayers getTopPlayers ();

  // Update the game state to reflect a player's win
  Game playerWins (Game games);

  // Logout a player
  boolean logout (Player players);
} // interface BoggledInterfaceOperations
