package BoggledGame;

/**
* BoggledGame/SendWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class SendWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public SendWordException value = null;

  public SendWordExceptionHolder ()
  {
  }

  public SendWordExceptionHolder (SendWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SendWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SendWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SendWordExceptionHelper.type ();
  }

}
