package BoggledGame;

/**
* BoggledGame/WordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class WordsHolder implements org.omg.CORBA.portable.Streamable
{
  public Words value = null;

  public WordsHolder ()
  {
  }

  public WordsHolder (Words initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordsHelper.type ();
  }

}
