package BoggledGame;

/**
* BoggledGame/BoggledInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/


// Define the WordyInterface interface
public final class BoggledInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledInterface value = null;

  public BoggledInterfaceHolder ()
  {
  }

  public BoggledInterfaceHolder (BoggledInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledInterfaceHelper.type ();
  }

}
