package BoggledGame;


/**
* BoggledGame/Round.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class Round implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  // unique ID for this round
  public char randomLetters[] = null;

  // the random letters for this round
  public Words wordsSentByPlayers[] = null;

  // words sent by players for this round
  public String winner = null;

  // username of the winner of this round (if any)
  public String status = null;

  public Round ()
  {
  } // ctor

  public Round (String _id, char[] _randomLetters, Words[] _wordsSentByPlayers, String _winner, String _status)
  {
    id = _id;
    randomLetters = _randomLetters;
    wordsSentByPlayers = _wordsSentByPlayers;
    winner = _winner;
    status = _status;
  } // ctor

} // class Round
