package BoggledGame;


/**
* BoggledGame/SendWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class SendWordException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public SendWordException ()
  {
    super(SendWordExceptionHelper.id());
  } // ctor

  public SendWordException (String _reason)
  {
    super(SendWordExceptionHelper.id());
    reason = _reason;
  } // ctor


  public SendWordException (String $reason, String _reason)
  {
    super(SendWordExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class SendWordException
