package BoggledGame;

/**
* BoggledGame/StartGameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Boggled.idl
* Sunday, June 9, 2024 8:26:25 PM SGT
*/

public final class StartGameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public StartGameException value = null;

  public StartGameExceptionHolder ()
  {
  }

  public StartGameExceptionHolder (StartGameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StartGameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StartGameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StartGameExceptionHelper.type ();
  }

}
